name: vitessce-figures-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - numpy
  - pandas
  - scipy
  - jupyterlab
  - numba
  - scanpy
  - anndata
  - snakemake
  - zarr
  - tifffile
  - scikit-image
  - h5py
  - tqdm
  - mudata
  - muon
  - celltypist
  - leidenalg
  - geopandas
  - pip
  - pip:
    - loompy
    - generate-tiff-offsets
    - ome-zarr
    - vitessce[all]
    - negspy
    - pybbi>=0.3.5
    #- mira-multiome>=1.0.1
    #- episcanpy
    - mudatasets[muon]
    - mofapy2
    - globus-cli
